### ISSUE TITLE
CI for Gobview

### ISSUE THREAD

**Issue by michael-schwarz** [goblint/gobview#11]
Given Gobview has a tendency to break, even if it still compiles, I think we should have a CI job that does not just test if it compiles but also if it works in the browser as expected,

I think an easy way to do this would be to include a `Loading everything has finished without issues` printout somewhere after the initialization of Gobview is finished and using a headless browser to check if that printout was produced as expected.

**Comment by sim642** [comment]
The additional inconvenience is that the Gobview CI runs only in Goblint's analyzer repo, where it's properly put into context using the git submodule. Nevertheless, if Gobview had some tests defined (to run with `dune runtest`), then we could easily run them in that Goblint workflow without having to leak more details there.

**Comment by stilscher** [comment]
A test for the CI was created in https://github.com/goblint/analyzer/pull/1037.
