### ISSUE TITLE
`Uncaught TypeError: runtime.integers_unsigned_init is not a function`

### ISSUE THREAD

**Issue by sofamaniac** [goblint/gobview#14]
Gobview is not loading anymore because of the error.

I believe it may be caused by a package that was added to goblint but not to gobview

**Comment by sim642** [comment]
I think adding this dependency should provide the necessary JS stubs: https://github.com/o1-labs/integers_stubs_js. I didn't look where the OCaml version of this dependency got added (transitively) though.

**Comment by sofamaniac** [comment]
Adding this dependency did solve, the problem, but now it demands some `ldouble` stubs (`TypeError: runtime.ldouble_init is not a function`), but I couldn't find any on github.

**Comment by sim642** [comment]
That seems to come from another set of stubs that yaml depends on: https://gitlab.com/nomadic-labs/ctypes_stubs_js.

**Comment by sofamaniac** [comment]
Yes, sorry I forgot to close the issue
