### ISSUE TITLE
Statement node states empty

### ISSUE THREAD

**Issue by sim642** [goblint/gobview#6]
Somehow statement nodes show no state, but the entry and return nodes do.
Comparing with the HTML output, it appears that their statement IDs are somehow different in Gobview than they were in the original Goblint run, so the right state cannot be found.

**Comment by keremc** [comment]
I think they set some global state because in the past the semantic search wouldn't function without them. That being said, semantic search seems to be broken anyway, so I can't actually test it.

**Comment by sim642** [comment]
The only global state I see those having is `Cil.sid_counter` and `Cil.new_sid`, so it might be something to do with that.

**Comment by keremc** [comment]
I commented out the lines that cause the issue, since the semantic search is broken even with them. Will create another issue for the semantic search.
